### ISSUE TITLE
Make empty sections work with "" and "{}"

### ISSUE THREAD

**Issue by kangarko** [tchristofferson/Config-Updater#29] opened 2023-05-08 07:32 UTC
Just thought it would be better to separate from the other Chinese letters issue:

"If it is an empty section, I believe it should be 'Prefix: {}' as the value, as that represents an empty config section. Also I think the link to your config is broken, so I can't see your config."

I have tons of users leaving it empty already, plus the users routinely forget to place {} after cleaning a section - could you just add an exception for this, please?

I hope it's not a big thing to add and it won't take a lot of time!
Thanks so much <3

**Comment by tchristofferson** [comment] 2023-07-03 22:19
Sorry about taking so long, but the issue where an empty ConfigurationSection is ignored should be fixed now (branch develop). When updating, if it is empty and ignored it would fail to add {} after the colon. Since there is nothing after the colon, it represents the value being null which is incorrect. Let me know if it is fixed an I will close this issue.

**Comment by kangarko** [comment] 2023-07-04 16:26
No problem and thanks!

When the ignored section is just set to the key name and there is no value, it does not work:

![a](https://i.imgur.com/UG9dTMd.png)

This is the error (ignore line numbers, they have changed): 

![b](https://i.imgur.com/hHPGJ0e.png)

Adding {} fixes the problem:

![a](https://i.imgur.com/ThWTEYX.png)

However, users are used to not having anything there so I am afraid of backward compatibility issues. Could you please fix this?

**Comment by broken1arrow** [comment] 2023-07-04 17:49
> No problem and thanks!
> 
> When the ignored section is just set to the key name and there is no value, it does not work:
> 
> ![a](https://camo.githubusercontent.com/4338cc9db50774445ae30cca0579f44a0aa6ecb6581a6355846dab9c3b25b4c0/68747470733a2f2f692e696d6775722e636f6d2f55473964544d642e706e67)
> 
> This is the error (ignore line numbers, they have changed):
> 
> ![b](https://camo.githubusercontent.com/2d36c932f6d060e735cf2f7560376a2ae247e9bb4badcfe2846c51b9ff1c1a27/68747470733a2f2f692e696d6775722e636f6d2f684850474a30652e706e67)
> 
> Adding {} fixes the problem:
> 
> ![a](https://camo.githubusercontent.com/ff65f2f17032053e941da4a4eed28f584ba38dcf1330cd2dfb5cb613c724977a/68747470733a2f2f692e696d6775722e636f6d2f546857544559582e706e67)
> 
> However, users are used to not having anything there so I am afraid of backward compatibility issues. Could you please fix this?

Currently, the code requires a value to be present in the default config. I conducted some tests and managed to resolve the error, but as a side effect, the corresponding key is removed from the file on disk. This occurs because the defaultConfig.getKeys() method ignores empty or null keys when writing the config. Therefore, addressing this issue would necessitate a significant code rewrite.

**Comment by tchristofferson** [comment] 2023-07-05 01:50
The issue is that if there is no {} it is still valid yml, but it is treated as null, not a configuration section.

**Comment by kangarko** [comment] 2023-07-05 06:05
I understand, so could you add it to your code such that a null is still a "valid" ignored section?

**Comment by broken1arrow** [comment] 2023-07-05 08:31
> I understand, so could you add it to your code such that a null is still a "valid" ignored section?

It's not so easy. It will then remove the key from the file on the disk, I don't know if that solution will work for all others use the api.

**Comment by kangarko** [comment] 2023-07-05 10:48
Could you make it so that when the key exists in the jar then it won't get removed, but simply ignored?

**Comment by broken1arrow** [comment] 2023-07-05 14:49
> Could you make it so that when the key exists in the jar then it won't get removed, but simply ignored?

it rewrite the file, so you can't simply ignore it. 

Here is the logic to write the config to a StringWriter, use BufferedWriter as help to write the lines.  
https://github.com/tchristofferson/Config-Updater/blob/58c9b3952d7dddb77c5501476c3a8e7b48488eca/src/main/java/com/tchristofferson/configupdater/ConfigUpdater.java#L46

It then convert the writer to string and write the data to the file. 
https://github.com/tchristofferson/Config-Updater/blob/58c9b3952d7dddb77c5501476c3a8e7b48488eca/src/main/java/com/tchristofferson/configupdater/ConfigUpdater.java#L42C1-L42C1

**Comment by kangarko** [comment] 2023-07-05 19:18
Hmm, I am not sure I understand.

Can you make it so that the {} will be automatically added if the key is null?

Items_Map:

->

Items_Map: {}

**Comment by broken1arrow** [comment] 2023-07-05 19:41
> Hmm, I am not sure I understand.
> 
> Can you make it so that the {} will be automatically added if the key is null?
> 
> Items_Map:
> 
> ->
> 
> Items_Map: {}

To make it clearer:

1. The implementation from Spigot/Bukkit SnakeYAML ignores all keys with no set values, which includes all values that are null or don’t have a trailing key.

2. The next step is to go through all ignored sections (if it is set). The tricky part is that it depends on the “fullkey” (number 3), so if that key never ends up in the fullkey or if it is a sub/trailing key to the fullkey, it will not be added to the config.

4. It writes all keys and values if they are not included in the ignored section (it will be set in the method you see below number 2).

However, I have an idea of how this issue could be solved together with another bug with ignored sections (currently it seems to update from the default file and not use the set value in the saved file on disk). I think both these issues could perhaps be fixed at the same time (I don’t currently have the time to test out my idea yet).

![writtingloop](https://github.com/tchristofferson/Config-Updater/assets/16368286/c7473a7d-6230-4c2d-a1a2-9dd2497b42df)

**Comment by tchristofferson** [comment] 2023-07-05 21:40
I am closing this issue. The {} should be placed in the config manually. I don't think we should update it because that goes against the logic of an ignored section. Whatever the value is in the current config is what it should stay as after the update. If it isn't an ignored section it will automatically be updated to have {} as long as that is what it is in the default config.

**Closed by tchristofferson** 2023-07-05 21:40 UTC
Labels: bug

**Comment by kangarko** [comment] 2023-07-08 12:45
I see, okay, I'll just notify my users about this in case they put a null there.
