### ISSUE TITLE
Could you please update it to fix some errors?

### ISSUE THREAD

**Issue by 404forever1** [tchristofferson/Config-Updater#36] opened 2024-12-22 15:38 UTC
It will make the Chinese characters in the configuration file of the 1.12.2 server garbled. I don't know why. I used java8, 21 is normal, but 1.12 requires java8
I tried to build it myself, but got an error
There are test failures.

Please refer to F:\开发\Java\Config-Updater-master\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.

**Comment by tchristofferson** [comment] 2024-12-23 06:23
Duplicate of #35. Also if you want to build it yourself you can do mvn package --DskipTests=true

**Closed by tchristofferson** 2024-12-23 06:23 UTC
Labels: duplicate
