### ISSUE TITLE
Comments break after map list

### ISSUE THREAD

**Issue by kangarko** [tchristofferson/Config-Updater#24] opened 2023-03-13 21:22 UTC
We have the following configuration: https://pastebin.com/B8Svtv0T

After calling ConfigUpdater#update, the file is partially "corrupted" as comments past the section of the image below no longer appear.

![a](https://i.imgur.com/2IFiYTH.png)

They strangelly reappear again after the map list sections are over:

![b](https://i.imgur.com/7SRpiLG.png)

I am using your exact code for a test case. I and my users would be really thankful if you could have a minute to look into this!

-Matej

**Comment by kangarko** [comment] 2023-03-13 21:23
Tagging my friend and collaborator who provided us his settings.yml if you need further information, @AdoNikeOFFICE

**Comment by tchristofferson** [comment] 2023-03-18 17:25
I will take a look at this. Are you ignoring any sections?

**Comment by AdoNikeOFFICE** [comment] 2023-03-18 17:31
> I will take a look at this. Are you ignoring any sections?

I tried ignoring and not ignoring, but result was the same.

**Comment by tchristofferson** [comment] 2023-03-18 21:43
The issue is with the KeyBuilder. I didn't think about a list of maps. The KeyBuilder believes Announcements.Permission, for example, is a valid key when it is actually the seconds property in the first list of maps. I will try and get a fix for this.

**Comment by kangarko** [comment] 2023-03-19 19:34
Awesome! Let me know your paypal or something and I'll donate because we've been using your library for our community for quite some time now!

**Comment by tchristofferson** [comment] 2023-03-25 18:43
Fixed with pull request #25. Use dependency version 2.1-SNAPSHOT as shown in readme.

**Comment by tchristofferson** [comment] 2023-03-25 19:06
@kangarko Didn't see your comment. My donation link on PayPal is https://www.paypal.com/paypalme/tchristoffers0n. You don't need to donate if you don't want to.

**Comment by kangarko** [comment] 2023-03-28 05:25
I love it! Thank you <3

@AdoNikeOFFICE can you please test on your software?

**Comment by kangarko** [comment] 2023-03-28 09:06
@tchristofferson I tried to boot your update with ChatControl (settings.yml > https://hastebin.com/share/irogerabol.yaml) and I am receiving the following issue.

It looks like ignoring a section which contains subsections where keys of the map of the ignored subsection are non-strings causes the problem.

<img width="860" alt="Screenshot 2023-03-28 at 11 03 26" src="https://user-images.githubusercontent.com/1918426/228186110-a19c44d2-67ee-47d1-b2e5-5181faacfbb2.png">

I attempted to change the (String s : map.keySet()) to "Object s" and then call toString but that results in another error: "java.lang.IllegalArgumentException: Invalid ignored section: Warning_Points.Sets.global.3"

**Comment by AdoNikeOFFICE** [comment] 2023-03-28 09:58
I also tested it and this is the result of settings.yml: https://pastebin.com/nGuNDbMZ. This is the original file: https://pastebin.com/verG1Wni. Some things weren't even saved at all, some things got shuffled around, and some comments are missing.

**Comment by tchristofferson** [comment] 2023-03-29 22:02
I know what the issue is with this, shouldn't take long to fix. What version of Spigot are you using?

**Comment by tchristofferson** [comment] 2023-03-29 22:35
What version of Spigot is being used?

**Comment by kangarko** [comment] 2023-03-30 07:45
We need it to work under the latest one (Paper/1.19.4) as well as Paper 1.8.8 for compatibility reasons. I can of course fork it and adjust for legacy versions afterwards if you don't have time.

**Comment by kangarko** [comment] 2023-03-30 07:46
In the above image, I used Paper/1.8.8. It ships with an outdated YAML library but it was not a problem before.

**Comment by AdoNikeOFFICE** [comment] 2023-03-30 08:04
> What version of Spigot is being used?

I tested it on 1.19.2.

**Comment by tchristofferson** [comment] 2023-04-01 19:36
I am looking into a solution using [eo-yaml](https://github.com/decorators-squad/eo-yaml) library so then I don't need to worry about formatting since Yaml is very dependent on formatting and is very nuanced.

**Comment by kangarko** [comment] 2023-04-02 17:09
The biggest downside is that we'd have to shade all classes of that library into our own library or have users rely on it which I am trying to avoid. Yours is literally just one class. It would be miles better just to keep things under 1 class and fix this one particular issue.

**Comment by tchristofferson** [comment] 2023-04-02 18:15
@kangarko I will shade eo-yaml so it is part of com.tchristofferson.configupdater. I get that it would be nice to keep it small, however, the code is hard to read, very sensitive to any changes, and there are probably cases where it won't work such as this case. You can keep using v2.0-SNAPSHOT which has been pretty stable and modify your yaml file so there aren't lists of maps.

**Comment by tchristofferson** [comment] 2023-04-03 02:17
Try using 2.1-SNAPSHOT and let me know if it works. Please get the latest 2.1-SNAPSHOT if you already tried to use it, or use the code in the develop branch.

**Comment by AdoNikeOFFICE** [comment] 2023-04-04 13:29
Tested with those commits and got similar or the same result: https://pastebin.com/wAyxUJN8.

**Comment by tchristofferson** [comment] 2023-04-06 22:37
I committed some more code to fix this. The tests are passing so I think it should be good. Can you give this another go?

**Comment by AdoNikeOFFICE** [comment] 2023-04-07 07:21
> I committed some more code to fix this. The tests are passing so I think it should be good. Can you give this another go?

I am going to give it a try in a minute.

**Comment by AdoNikeOFFICE** [comment] 2023-04-07 08:40
@tchristofferson, this is the result: https://pastebin.com/pDfm3zXC. This is the original file: https://pastebin.com/VuCYwpEC.

You can already see progress there, but in the middle of the file it still messes up those comments for some reason.

**Comment by kangarko** [comment] 2023-04-07 17:52
@AdoNikeOFFICE This is invalid:

:): ☺

You need to change this to

":)": "☺"

Can you retry after you changed all of the Emoji keys? (Also see if there are any other sections of your settings with : in the key name, you need to put "" around it).

**Comment by AdoNikeOFFICE** [comment] 2023-04-07 18:07
> @AdoNikeOFFICE This is invalid:
> 
> `:): ☺`
> 
> You need to change this to
> 
> `":)": "☺"`
> 
> Can you retry after you changed all of the Emoji keys? (Also see if there are any other sections of your settings with : in the key name, you need to put "" around it).

See the original file, `:): ☺` is changed like that when saving.

**Comment by tchristofferson** [comment] 2023-04-10 22:35
I think it is fixed now. I used your entire config and the test passes. Let me know if its fixed.

**Comment by AdoNikeOFFICE** [comment] 2023-04-11 06:53
I confirm, it works!

**Closed** 2023-04-11 20:51 UTC

**Comment by kangarko** [comment] 2023-04-13 06:50
Thanks everyone!
